// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"

	types "github.com/DataDog/KubeHound/pkg/globals/types"
	mock "github.com/stretchr/testify/mock"
)

// RoleIngestor is an autogenerated mock type for the RoleIngestor type
type RoleIngestor struct {
	mock.Mock
}

type RoleIngestor_Expecter struct {
	mock *mock.Mock
}

func (_m *RoleIngestor) EXPECT() *RoleIngestor_Expecter {
	return &RoleIngestor_Expecter{mock: &_m.Mock}
}

// Complete provides a mock function with given fields: _a0
func (_m *RoleIngestor) Complete(_a0 context.Context) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RoleIngestor_Complete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Complete'
type RoleIngestor_Complete_Call struct {
	*mock.Call
}

// Complete is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *RoleIngestor_Expecter) Complete(_a0 interface{}) *RoleIngestor_Complete_Call {
	return &RoleIngestor_Complete_Call{Call: _e.mock.On("Complete", _a0)}
}

func (_c *RoleIngestor_Complete_Call) Run(run func(_a0 context.Context)) *RoleIngestor_Complete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *RoleIngestor_Complete_Call) Return(_a0 error) *RoleIngestor_Complete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RoleIngestor_Complete_Call) RunAndReturn(run func(context.Context) error) *RoleIngestor_Complete_Call {
	_c.Call.Return(run)
	return _c
}

// IngestRole provides a mock function with given fields: _a0, _a1
func (_m *RoleIngestor) IngestRole(_a0 context.Context, _a1 types.RoleType) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.RoleType) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RoleIngestor_IngestRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IngestRole'
type RoleIngestor_IngestRole_Call struct {
	*mock.Call
}

// IngestRole is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 types.RoleType
func (_e *RoleIngestor_Expecter) IngestRole(_a0 interface{}, _a1 interface{}) *RoleIngestor_IngestRole_Call {
	return &RoleIngestor_IngestRole_Call{Call: _e.mock.On("IngestRole", _a0, _a1)}
}

func (_c *RoleIngestor_IngestRole_Call) Run(run func(_a0 context.Context, _a1 types.RoleType)) *RoleIngestor_IngestRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(types.RoleType))
	})
	return _c
}

func (_c *RoleIngestor_IngestRole_Call) Return(_a0 error) *RoleIngestor_IngestRole_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RoleIngestor_IngestRole_Call) RunAndReturn(run func(context.Context, types.RoleType) error) *RoleIngestor_IngestRole_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewRoleIngestor interface {
	mock.TestingT
	Cleanup(func())
}

// NewRoleIngestor creates a new instance of RoleIngestor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRoleIngestor(t mockConstructorTestingTNewRoleIngestor) *RoleIngestor {
	mock := &RoleIngestor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
