FROM golang:1.22 AS build-stage

COPY go.mod go.sum ./
RUN go mod download

COPY pkg ./pkg
COPY Makefile .
COPY cmd ./cmd
COPY configs ./configs
COPY deployments ./deployments

RUN GOOS=linux GOARCH=amd64 go build -o "./bin/build/kubehound" ./cmd/kubehound/

FROM registry.ddbuild.io/images/base/gbi-ubuntu_2404:release
# FROM ubuntu:24.04 AS build-release-stage

WORKDIR /

COPY --from=build-stage /go/bin/build/kubehound /kubehound

EXPOSE 9000

ENTRYPOINT ["/kubehound"]
CMD  ["serve"]
