run:
  # Default: 1m
  timeout: 5m

linters:
  disable-all: true
  # Enable specific linter
  # https://golangci-lint.run/usage/linters/#enabled-by-default
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    # - cyclop
    - decorder
    - dogsled
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - execinquery
    - exhaustive
    # - exhaustruct
    - exportloopref
    - forbidigo
    - forcetypeassert
    # - gci
    - ginkgolinter
    - gocheckcompilerdirectives
    # - gochecknoglobals
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    # - goerr113 # Would probably be best. But lets ignore for now
    - gofmt
    # - gofumpt
    - goheader
    - goimports
    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - grouper
    - importas
    - ineffassign
    - interfacebloat
    # - ireturn
    - loggercheck
    - maintidx
    - makezero
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - reassign
    # - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    # - stylecheck TODO reeanble
    - tenv
    - testableexamples
    # - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    # - whitespace
    # - wrapcheck #TODO: add it back later potentially?