site_name: KubeHound
site_url: https://kubehound.io
repo_url: https://github.com/DataDog/KubeHound
repo_name: datadog/KubeHound
plugins:
  - search
  - awesome-pages
extra_css:
  - css/extra.css
theme:
  name: material
  logo: ./logo.png
  favicon: ./logo.png
  palette:
    - scheme: default
      primary: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  use_directory_urls: true
  extra_javascript:
    - path: js/tablesort.js #TODO not working
  extra:
    social: {}

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.magiclink
  - tables
  - meta
  - abbr
  - def_list
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - footnotes
  - markdown_captions
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - KubeHound:
      - index.md
      - Architecture: architecture.md
      - Terminology: terminology.md
      - Frequently Asked Questions: faq.md
      - Comparison with Other Tools: comparison.md
      - Contributing: contributing.md
      - References: references.md
      - Workshop: workshop.md
  - User Guide:
      - Getting Started: user-guide/getting-started.md
      - Advanced config: user-guide/advanced-configuration.md
      - Local Common Operations: user-guide/common-operations.md
      - Troubleshooting: user-guide/troubleshooting.md
  - KubeHound as a Serivce:
      - Getting Started: khaas/getting-started.md
      - Advanced config: khaas/advanced-configuration.md
      - Deployment: khaas/deployment.md
  - Developer Guide:
      - Getting Started: dev-guide/getting-started.md
      - Testing: dev-guide/testing.md
      - Wiki: dev-guide/wiki.md
      - Datadog setup: dev-guide/datadog.md
  - Attack Techniques Reference:
      - ... |reference/*/*.md
      #- Attacks: reference/attacks/index.md
      #- Entities: reference/entities/index.md
      #- ... | reference/attacks/*.md
      #- ... | reference/entities/*.md
  - Query Library:
      - queries/index.md
      - queries/dsl.md
      - queries/metrics.md
      - "Sample queries": queries/gremlin.md

copyright: Copyright 2024-Present Datadog, Inc.
