#
# Default Datadog KubeHound configuration
# NOTE: this is optimized for large clusters in the Datadog environment
#

# K8s collector configuration
collector:
  # Type of collector to use
  type: live-k8s-api-collector

  # Live collector configuration
  live:
    # Rate limit of requests/second to the Kubernetes API
    rate_limit_per_second: 75

    # Number of pages to buffer
    page_buffer_size: 50

# General storage configuration
storage:
  # Number of connection retries before declaring an error
  retry: 5

  # Delay between connection retries
  retry_delay: 10s

# Store database configuration
mongodb:
  # Connection URL to the mongo DB instance
  url: "mongodb://localhost:27017"

  # Timeout on requests to the mongo DB instance
  connection_timeout: 30s

# Graph database configuration
janusgraph:
  # Connection URL to the JanusGraph DB instance
  url: "ws://localhost:8182/gremlin"

  # Timeout on requests to the JanusGraph DB instance
  connection_timeout: 30s

# Datadog telemetry configuration
telemetry:
  # Whether to enable Datadog telemetry (default false)
  enable: true

  # Default tags to add to all telemetry (free form key-value map)
  tags:
    team: ase

  # Statsd configuration for metics support
  statsd:
    # URL to send statsd data to the Datadog agent
    url: "127.0.0.1:8225"

  # Tracer configuration for APM support
  tracer:
    # URL to send tracer data to the Datadog agent
    url: "127.0.0.1:8226"

# Graph builder configuration
builder:
  # Vertex builder configuration
  vertex:
    # Batch size for vertex inserts
    batch_size: 500

  # Edge builder configuration
  edge:
    worker_pool_size: 2

    # Batch size for edge inserts
    batch_size: 500
    
    # Cluster impact batch size for edge inserts
    batch_size_cluster_impact: 10

    # Enable for large clusters to prevent number of edges growing exponentially
    large_cluster_optimizations: true
