#
# Default KubeHound configuration
# NOTE: this is optimized for smaller clusters of 1-2k pods
#

# General storage configuration
storage:
  # Number of connection retries before declaring an error
  retry: 5

  # Delay between connection retries
  retry_delay: 10s

# Store database configuration
mongodb:
  # Connection URL to the mongo DB instance
  url: "mongodb://localhost:27017"

  # Timeout on requests to the mongo DB instance
  connection_timeout: 30s

# Graph database configuration
janusgraph:
  # Connection URL to the JanusGraph DB instance
  url: "ws://localhost:8182/gremlin"

  # Timeout on requests to the JanusGraph DB instance
  connection_timeout: 30s

# Graph builder configuration
builder:
  # Vertex builder configuration
  vertex:
    # Batch size for vertex inserts
    batch_size: 500

  # Edge builder configuration
  edge:
    worker_pool_size: 2

    # Batch size for edge inserts
    batch_size: 500
    
    # Cluster impact batch size for edge inserts
    batch_size_cluster_impact: 10
    
    # Enable for large clusters to prevent number of edges growing exponentially
    large_cluster_optimizations: true

# Ingestor configuration (for KHaaS)
ingestor:
  blob:
    bucket: "" # (i.e.: s3://<your_bucket>)
    region: "" # (i.e.: us-west-2)
  temp_dir: "/tmp/kubehound"
  archive_name: "archive.tar.gz"
  max_archive_size: 2147483648 # 2GB
  api: # GRPC endpoint for the ingestor
    endpoint: "127.0.0.1:9000"
    insecure: true