apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ $.Chart.Name }}-db"
  namespace: {{ $.Release.Namespace }}
  labels:
    app: "{{ $.Chart.Name }}-db"
    service: {{ $.Chart.Name }}
    chart_version: {{ $.Chart.Version }}
    chart_name: {{ $.Chart.Name }}
    team: {{ $.Values.team }}

spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ $.Chart.Name }}-db"
  template:
    metadata:
      labels:
        app: "{{ $.Chart.Name }}-db"
        service: {{ $.Chart.Name }}
        team: {{ $.Values.team }}
        chart_name: {{ $.Chart.Name }}
    spec:
      containers:
      - name: {{ $.Chart.Name }}-db
        image: "{{ $.Values.services.db.image }}:{{ $.Values.services.db.version }}"
        imagePullPolicy: Always
        resources:
          requests:
            cpu: {{ $.Values.services.db.resources.requests.cpu }}
            memory: {{ $.Values.services.db.resources.requests.memory }}
          limits:
            cpu: {{ $.Values.services.db.resources.limits.cpu }}
            memory: {{ $.Values.services.db.resources.limits.memory }}
        ports:
          - name: db
            containerPort: {{ $.Values.services.db.port }}
