apiVersion: batch/v1
kind: CronJob
metadata:
  name: "{{ $.Chart.Name }}-collector"
  namespace: {{ $.Release.Namespace }}
  labels:
    app: "{{ $.Chart.Name }}-collector"
    service: {{ $.Chart.Name }}
    chart_version: {{ $.Chart.Version }}
    chart_name: {{ $.Chart.Name }}
    team: {{ $.Values.team }}
spec:
  schedule: "0,30 * * * *"
  failedJobsHistoryLimit: 5
  successfulJobsHistoryLimit: 5
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: "{{ $.Chart.Name }}-collector"
            service: {{ $.Chart.Name }}
            team: {{ $.Values.team }}
            chart_name: {{ $.Chart.Name }}
          restartPolicy: Never
          serviceAccountName: "{{ $.Chart.Name }}-collector"
          containers:
          - name: {{ $.Chart.Name }}-collector
            image: "{{ $.Values.services.collector.image }}:{{ $.Values.services.collector.version}}"
            imagePullPolicy: Always
            resources:
              requests:
                cpu: {{ $.Values.services.collector.resources.requests.cpu }}
                memory: {{ $.Values.services.collector.resources.requests.memory }}
              limits:
                cpu: {{ $.Values.services.collector.resources.limits.cpu }}
                memory: {{ $.Values.services.collector.resources.limits.memory }}
            command: ["/kubehound","dump","remote","--khaas-server","{{ $.Values.services.collector.khaas_server }}","--bucket","{{ $.Values.services.ingestor.bucket_url }}","--region","us-east-1"]
            env:
              - name: KH_LOG_FORMAT
                value: json
              - name: KH_K8S_CLUSTER_NAME_ENV_PTR
                value: K8S_CLUSTER_NAME
