apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ $.Chart.Name }}-ingestor"
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $.Chart.Name }}-ingestor
    service: {{ $.Chart.Name }}
    team: {{ $.Values.team }}
    chart_name: {{ $.Chart.Name }}
    chart_version: {{ $.Chart.Version }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Chart.Name }}-collector
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $.Chart.Name }}-collector
    service: {{ $.Chart.Name }}
    team: {{ $.Values.team }}
    chart_name: {{ $.Chart.Name }}
    chart_version: {{ $.Chart.Version }}
