// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"

	cache "github.com/DataDog/KubeHound/pkg/kubehound/storage/cache"

	edge "github.com/DataDog/KubeHound/pkg/kubehound/graph/edge"

	graphdb "github.com/DataDog/KubeHound/pkg/kubehound/storage/graphdb"

	mock "github.com/stretchr/testify/mock"

	vertex "github.com/DataDog/KubeHound/pkg/kubehound/graph/vertex"
)

// Provider is an autogenerated mock type for the Provider type
type Provider struct {
	mock.Mock
}

type Provider_Expecter struct {
	mock *mock.Mock
}

func (_m *Provider) EXPECT() *Provider_Expecter {
	return &Provider_Expecter{mock: &_m.Mock}
}

// Clear provides a mock function with given fields: ctx
func (_m *Provider) Clear(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Provider_Clear_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clear'
type Provider_Clear_Call struct {
	*mock.Call
}

// Clear is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Provider_Expecter) Clear(ctx interface{}) *Provider_Clear_Call {
	return &Provider_Clear_Call{Call: _e.mock.On("Clear", ctx)}
}

func (_c *Provider_Clear_Call) Run(run func(ctx context.Context)) *Provider_Clear_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Provider_Clear_Call) Return(_a0 error) *Provider_Clear_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Provider_Clear_Call) RunAndReturn(run func(context.Context) error) *Provider_Clear_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function with given fields: ctx
func (_m *Provider) Close(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Provider_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type Provider_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Provider_Expecter) Close(ctx interface{}) *Provider_Close_Call {
	return &Provider_Close_Call{Call: _e.mock.On("Close", ctx)}
}

func (_c *Provider_Close_Call) Run(run func(ctx context.Context)) *Provider_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Provider_Close_Call) Return(_a0 error) *Provider_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Provider_Close_Call) RunAndReturn(run func(context.Context) error) *Provider_Close_Call {
	_c.Call.Return(run)
	return _c
}

// EdgeWriter provides a mock function with given fields: ctx, e, opts
func (_m *Provider) EdgeWriter(ctx context.Context, e edge.Builder, opts ...graphdb.WriterOption) (graphdb.AsyncEdgeWriter, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, e)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 graphdb.AsyncEdgeWriter
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, edge.Builder, ...graphdb.WriterOption) (graphdb.AsyncEdgeWriter, error)); ok {
		return rf(ctx, e, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, edge.Builder, ...graphdb.WriterOption) graphdb.AsyncEdgeWriter); ok {
		r0 = rf(ctx, e, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(graphdb.AsyncEdgeWriter)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, edge.Builder, ...graphdb.WriterOption) error); ok {
		r1 = rf(ctx, e, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Provider_EdgeWriter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EdgeWriter'
type Provider_EdgeWriter_Call struct {
	*mock.Call
}

// EdgeWriter is a helper method to define mock.On call
//   - ctx context.Context
//   - e edge.Builder
//   - opts ...graphdb.WriterOption
func (_e *Provider_Expecter) EdgeWriter(ctx interface{}, e interface{}, opts ...interface{}) *Provider_EdgeWriter_Call {
	return &Provider_EdgeWriter_Call{Call: _e.mock.On("EdgeWriter",
		append([]interface{}{ctx, e}, opts...)...)}
}

func (_c *Provider_EdgeWriter_Call) Run(run func(ctx context.Context, e edge.Builder, opts ...graphdb.WriterOption)) *Provider_EdgeWriter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]graphdb.WriterOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(graphdb.WriterOption)
			}
		}
		run(args[0].(context.Context), args[1].(edge.Builder), variadicArgs...)
	})
	return _c
}

func (_c *Provider_EdgeWriter_Call) Return(_a0 graphdb.AsyncEdgeWriter, _a1 error) *Provider_EdgeWriter_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Provider_EdgeWriter_Call) RunAndReturn(run func(context.Context, edge.Builder, ...graphdb.WriterOption) (graphdb.AsyncEdgeWriter, error)) *Provider_EdgeWriter_Call {
	_c.Call.Return(run)
	return _c
}

// HealthCheck provides a mock function with given fields: ctx
func (_m *Provider) HealthCheck(ctx context.Context) (bool, error) {
	ret := _m.Called(ctx)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (bool, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Provider_HealthCheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HealthCheck'
type Provider_HealthCheck_Call struct {
	*mock.Call
}

// HealthCheck is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Provider_Expecter) HealthCheck(ctx interface{}) *Provider_HealthCheck_Call {
	return &Provider_HealthCheck_Call{Call: _e.mock.On("HealthCheck", ctx)}
}

func (_c *Provider_HealthCheck_Call) Run(run func(ctx context.Context)) *Provider_HealthCheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Provider_HealthCheck_Call) Return(_a0 bool, _a1 error) *Provider_HealthCheck_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Provider_HealthCheck_Call) RunAndReturn(run func(context.Context) (bool, error)) *Provider_HealthCheck_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function with given fields:
func (_m *Provider) Name() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Provider_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type Provider_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *Provider_Expecter) Name() *Provider_Name_Call {
	return &Provider_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *Provider_Name_Call) Run(run func()) *Provider_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Provider_Name_Call) Return(_a0 string) *Provider_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Provider_Name_Call) RunAndReturn(run func() string) *Provider_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Raw provides a mock function with given fields:
func (_m *Provider) Raw() interface{} {
	ret := _m.Called()

	var r0 interface{}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// Provider_Raw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Raw'
type Provider_Raw_Call struct {
	*mock.Call
}

// Raw is a helper method to define mock.On call
func (_e *Provider_Expecter) Raw() *Provider_Raw_Call {
	return &Provider_Raw_Call{Call: _e.mock.On("Raw")}
}

func (_c *Provider_Raw_Call) Run(run func()) *Provider_Raw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Provider_Raw_Call) Return(_a0 interface{}) *Provider_Raw_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Provider_Raw_Call) RunAndReturn(run func() interface{}) *Provider_Raw_Call {
	_c.Call.Return(run)
	return _c
}

// VertexWriter provides a mock function with given fields: ctx, v, c, opts
func (_m *Provider) VertexWriter(ctx context.Context, v vertex.Builder, c cache.CacheProvider, opts ...graphdb.WriterOption) (graphdb.AsyncVertexWriter, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, v, c)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 graphdb.AsyncVertexWriter
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, vertex.Builder, cache.CacheProvider, ...graphdb.WriterOption) (graphdb.AsyncVertexWriter, error)); ok {
		return rf(ctx, v, c, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, vertex.Builder, cache.CacheProvider, ...graphdb.WriterOption) graphdb.AsyncVertexWriter); ok {
		r0 = rf(ctx, v, c, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(graphdb.AsyncVertexWriter)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, vertex.Builder, cache.CacheProvider, ...graphdb.WriterOption) error); ok {
		r1 = rf(ctx, v, c, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Provider_VertexWriter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VertexWriter'
type Provider_VertexWriter_Call struct {
	*mock.Call
}

// VertexWriter is a helper method to define mock.On call
//   - ctx context.Context
//   - v vertex.Builder
//   - c cache.CacheProvider
//   - opts ...graphdb.WriterOption
func (_e *Provider_Expecter) VertexWriter(ctx interface{}, v interface{}, c interface{}, opts ...interface{}) *Provider_VertexWriter_Call {
	return &Provider_VertexWriter_Call{Call: _e.mock.On("VertexWriter",
		append([]interface{}{ctx, v, c}, opts...)...)}
}

func (_c *Provider_VertexWriter_Call) Run(run func(ctx context.Context, v vertex.Builder, c cache.CacheProvider, opts ...graphdb.WriterOption)) *Provider_VertexWriter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]graphdb.WriterOption, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(graphdb.WriterOption)
			}
		}
		run(args[0].(context.Context), args[1].(vertex.Builder), args[2].(cache.CacheProvider), variadicArgs...)
	})
	return _c
}

func (_c *Provider_VertexWriter_Call) Return(_a0 graphdb.AsyncVertexWriter, _a1 error) *Provider_VertexWriter_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Provider_VertexWriter_Call) RunAndReturn(run func(context.Context, vertex.Builder, cache.CacheProvider, ...graphdb.WriterOption) (graphdb.AsyncVertexWriter, error)) *Provider_VertexWriter_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewProvider interface {
	mock.TestingT
	Cleanup(func())
}

// NewProvider creates a new instance of Provider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewProvider(t mockConstructorTestingTNewProvider) *Provider {
	mock := &Provider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
