// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// AsyncVertexWriter is an autogenerated mock type for the AsyncVertexWriter type
type AsyncVertexWriter struct {
	mock.Mock
}

type AsyncVertexWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *AsyncVertexWriter) EXPECT() *AsyncVertexWriter_Expecter {
	return &AsyncVertexWriter_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with given fields: ctx
func (_m *AsyncVertexWriter) Close(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AsyncVertexWriter_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type AsyncVertexWriter_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *AsyncVertexWriter_Expecter) Close(ctx interface{}) *AsyncVertexWriter_Close_Call {
	return &AsyncVertexWriter_Close_Call{Call: _e.mock.On("Close", ctx)}
}

func (_c *AsyncVertexWriter_Close_Call) Run(run func(ctx context.Context)) *AsyncVertexWriter_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *AsyncVertexWriter_Close_Call) Return(_a0 error) *AsyncVertexWriter_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AsyncVertexWriter_Close_Call) RunAndReturn(run func(context.Context) error) *AsyncVertexWriter_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Flush provides a mock function with given fields: ctx
func (_m *AsyncVertexWriter) Flush(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AsyncVertexWriter_Flush_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Flush'
type AsyncVertexWriter_Flush_Call struct {
	*mock.Call
}

// Flush is a helper method to define mock.On call
//   - ctx context.Context
func (_e *AsyncVertexWriter_Expecter) Flush(ctx interface{}) *AsyncVertexWriter_Flush_Call {
	return &AsyncVertexWriter_Flush_Call{Call: _e.mock.On("Flush", ctx)}
}

func (_c *AsyncVertexWriter_Flush_Call) Run(run func(ctx context.Context)) *AsyncVertexWriter_Flush_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *AsyncVertexWriter_Flush_Call) Return(_a0 error) *AsyncVertexWriter_Flush_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AsyncVertexWriter_Flush_Call) RunAndReturn(run func(context.Context) error) *AsyncVertexWriter_Flush_Call {
	_c.Call.Return(run)
	return _c
}

// Queue provides a mock function with given fields: ctx, v
func (_m *AsyncVertexWriter) Queue(ctx context.Context, v interface{}) error {
	ret := _m.Called(ctx, v)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}) error); ok {
		r0 = rf(ctx, v)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AsyncVertexWriter_Queue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Queue'
type AsyncVertexWriter_Queue_Call struct {
	*mock.Call
}

// Queue is a helper method to define mock.On call
//   - ctx context.Context
//   - v interface{}
func (_e *AsyncVertexWriter_Expecter) Queue(ctx interface{}, v interface{}) *AsyncVertexWriter_Queue_Call {
	return &AsyncVertexWriter_Queue_Call{Call: _e.mock.On("Queue", ctx, v)}
}

func (_c *AsyncVertexWriter_Queue_Call) Run(run func(ctx context.Context, v interface{})) *AsyncVertexWriter_Queue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interface{}))
	})
	return _c
}

func (_c *AsyncVertexWriter_Queue_Call) Return(_a0 error) *AsyncVertexWriter_Queue_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AsyncVertexWriter_Queue_Call) RunAndReturn(run func(context.Context, interface{}) error) *AsyncVertexWriter_Queue_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewAsyncVertexWriter interface {
	mock.TestingT
	Cleanup(func())
}

// NewAsyncVertexWriter creates a new instance of AsyncVertexWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAsyncVertexWriter(t mockConstructorTestingTNewAsyncVertexWriter) *AsyncVertexWriter {
	mock := &AsyncVertexWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
