package edge

import (
	"context"
	"database/sql"
	"fmt"

	"github.com/DataDog/KubeHound/pkg/kubehound/graph/types"
	"github.com/DataDog/KubeHound/pkg/kubehound/graph/vertex"
	"github.com/DataDog/KubeHound/pkg/kubehound/models/converter"
	"github.com/DataDog/KubeHound/pkg/kubehound/models/store"
	gremlin "github.com/apache/tinkerpop/gremlin-go/v3/driver"
)

func init() {
	Register(&PodPatch{}, RegisterGraphMutation)
}

type PodPatch struct {
	BaseEdge
}

type podPatchGroup struct {
	Role int64 `json:"role"`
}

func (e *PodPatch) Label() string {
	return "POD_PATCH"
}

func (e *PodPatch) Name() string {
	return "PodPatch"
}

func (e *PodPatch) AttckTechniqueID() AttckTechniqueID {
	return AttckTechniqueContainerAdministrationCommand
}

func (e *PodPatch) AttckTacticID() AttckTacticID {
	return AttckTacticExecution
}

func (e *PodPatch) BatchSize() int {
	if e.cfg.LargeClusterOptimizations {
		// Under optimization this becomes a very cheap operation
		return e.cfg.BatchSize
	}

	return e.cfg.BatchSizeClusterImpact
}

func (e *PodPatch) processor(ctx context.Context, oic *converter.ObjectIDConverter, entry any) (any, error) {
	typed, ok := entry.(*podPatchGroup)
	if !ok {
		return nil, fmt.Errorf("invalid type passed to processor: %T", entry)
	}

	rid, err := oic.GraphID(ctx, store.Hex(typed.Role))
	if err != nil {
		return nil, fmt.Errorf("%s edge role id convert: %w", e.Label(), err)
	}

	if e.cfg.LargeClusterOptimizations {
		return map[any]any{
			gremlin.T.Label: vertex.PermissionSetLabel,
			gremlin.T.Id:    rid,
		}, nil
	}

	return rid, nil
}

func (e *PodPatch) Traversal() types.EdgeTraversal {
	return func(source *gremlin.GraphTraversalSource, inserts []any) *gremlin.GraphTraversal {
		g := source.GetGraphTraversal()
		if e.cfg.LargeClusterOptimizations {
			// In large clusters this can explode the number of edges and we can safely assume this is a critical issue
			g.
				Inject(inserts).
				Unfold().
				As("rpp").
				MergeV(__.Select("rpp")).
				Option(gremlin.Merge.OnCreate, __.Fail("missing role vertex on POD_PATCH insert")).
				Option(gremlin.Merge.OnMatch, map[any]any{
					"critical": true,
				}).
				AddE(e.Label()).
				Property("attckTechniqueID", string(e.AttckTechniqueID())).
				Property("attckTacticID", string(e.AttckTacticID())).
				Barrier().Limit(0)
		} else {
			// In smaller clusters we can still show the (large set of) attack paths generated by this attack
			g.V().
				Has("runID", e.runtime.RunID.String()).
				Has("cluster", e.runtime.Cluster.Name).
				Has("class", "Pod").
				As("p").
				V(inserts...).
				Has("critical", false).
				AddE(e.Label()).
				To("p").
				Property("attckTechniqueID", string(e.AttckTechniqueID())).
				Property("attckTacticID", string(e.AttckTacticID())).
				Barrier().Limit(0)
		}

		return g
	}
}

// Stream finds all roles that have pod/patch or equivalent wildcard permissions.
func (e *PodPatch) Stream(ctx context.Context, db *sql.DB, w types.EdgeWriter) error {
	oic := converter.NewObjectID(db)
	rows, err := db.QueryContext(ctx, `
		SELECT DISTINCT ps.id FROM permissionsets ps, json_each(ps.rules) AS r
		WHERE ps.is_namespaced = 0 AND ps.run_id = ? AND ps.cluster_name = ?
		AND EXISTS (SELECT 1 FROM json_each(json_extract(r.value, '$.apiGroups')) WHERE value IN ('', '*'))
		AND EXISTS (SELECT 1 FROM json_each(json_extract(r.value, '$.resources')) WHERE value IN ('pods', 'cronjobs', 'daemonsets', 'deployments', 'jobs', 'replicasets', 'replicationcontrollers', 'statefulsets', '*'))
		AND EXISTS (SELECT 1 FROM json_each(json_extract(r.value, '$.verbs')) WHERE value IN ('patch', 'update', '*'))
		AND (json_extract(r.value, '$.resourceNames') IS NULL OR json_extract(r.value, '$.resourceNames') = '[]')`,
		e.runtime.RunID.String(), e.runtime.Cluster.Name)
	if err != nil {
		return err
	}
	defer rows.Close()
	for rows.Next() {
		var g podPatchGroup
		if err := rows.Scan(&g.Role); err != nil {
			return err
		}
		insert, err := e.processor(ctx, oic, &g)
		if err != nil {
			return err
		}
		if err := w.Queue(ctx, insert); err != nil {
			return err
		}
	}
	if err := rows.Err(); err != nil {
		return err
	}
	return w.Flush(ctx)
}
