package edge

import (
	"context"
	"fmt"

	"github.com/DataDog/KubeHound/pkg/kubehound/graph/adapter"
	"github.com/DataDog/KubeHound/pkg/kubehound/graph/types"
	"github.com/DataDog/KubeHound/pkg/kubehound/models/converter"
	"github.com/DataDog/KubeHound/pkg/kubehound/risk"
	"github.com/DataDog/KubeHound/pkg/kubehound/storage/cache"
	"github.com/DataDog/KubeHound/pkg/kubehound/storage/storedb"
	"github.com/DataDog/KubeHound/pkg/kubehound/store/collections"
	gremlin "github.com/apache/tinkerpop/gremlin-go/v3/driver"
	"go.mongodb.org/mongo-driver/bson"
)

const (
	ClusterRoleBindName = "RoleBindClusteRoleBindingbClusterRoleClusterRole"
)

func init() {
	Register(&RoleBindCrbCrCr{}, RegisterDefault)
}

type RoleBindCrbCrCr struct {
	BaseEdge
}

func (e *RoleBindCrbCrCr) Label() string {
	return RoleBindLabel
}

func (e *RoleBindCrbCrCr) Name() string {
	return ClusterRoleBindName
}

func (e *RoleBindCrbCrCr) Processor(ctx context.Context, oic *converter.ObjectIDConverter, entry any) (any, error) {
	typed, ok := entry.(*roleBindGroup)
	if !ok {
		return nil, fmt.Errorf("invalid type passed to processor: %T", entry)
	}

	psid, err := oic.GraphID(ctx, typed.PermissionSet.Hex())
	if err != nil {
		return nil, fmt.Errorf("%s edge PermissionSet id convert: %w", e.Label(), err)
	}

	return psid, nil
}

func (e *RoleBindCrbCrCr) Traversal() types.EdgeTraversal {
	return func(source *gremlin.GraphTraversalSource, inserts []any) *gremlin.GraphTraversal {
		g := source.GetGraphTraversal()

		// Gathering all sensitives roles
		sensitiveRoles := make([]string, 0, len(risk.CriticalRoleMap))
		for k := range risk.CriticalRoleMap {
			sensitiveRoles = append(sensitiveRoles, k)
		}

		if e.cfg.LargeClusterOptimizations {
			// For larger clusters simply target specific roles to reduce number of attack paths
			g.V().
				HasLabel("PermissionSet").
				Has("isNamespaced", false).
				// Temporary measure, until we scan and flag for sensitive roles
				Has("role", P.Within(sensitiveRoles)).
				As("r").
				V(inserts...).
				Has("critical", false).
				AddE(e.Label()).
				To("r").
				Barrier().Limit(0)
		} else {
			// In smaller clusters we can still show the (large set of) attack paths generated by this attack
			g.V().
				HasLabel("PermissionSet").
				Has("isNamespaced", false).
				As("i").
				V(inserts...).
				Has("critical", false).
				AddE(e.Label()).
				To("i").
				Barrier().Limit(0)
		}

		return g
	}
}

func (e *RoleBindCrbCrCr) Stream(ctx context.Context, store storedb.Provider, c cache.CacheReader,
	callback types.ProcessEntryCallback, complete types.CompleteQueryCallback) error {

	permissionSets := adapter.MongoDB(store).Collection(collections.PermissionSetName)
	// Handle clusterrolebindings against clusterroles
	pipeline := []bson.M{
		// $match stage
		{
			"$match": bson.M{
				"is_namespaced": false,
				"rules": bson.M{
					"$elemMatch": bson.M{
						"$or": []bson.M{
							{"apigroups": "*"},
							{"apigroups": "rbac.authorization.k8s.io"},
						},
					},
				},
				"$and": []bson.M{
					{
						"rules": bson.M{
							"$elemMatch": bson.M{
								"$and": []bson.M{
									{
										"$or": []bson.M{
											{"verbs": "create"},
											{"verbs": "*"},
										},
									},
									{
										"$or": []bson.M{
											{"resources": "clusterrolebindings"},
											{"resources": "rolebindings"},
											{"resources": "*"},
										},
									},
									{
										"$or": []bson.M{
											{"resourcenames": nil},
											{"resourcenames": "*"},
										},
									},
								},
							},
						},
					},
					{
						"rules": bson.M{
							"$elemMatch": bson.M{
								"$and": []bson.M{
									{
										"$or": []bson.M{
											{"verbs": "bind"},
											{"verbs": "*"},
										},
									},
									{
										"$or": []bson.M{
											{"resources": "clusterroles"},
											{"resources": "*"},
										},
									},
									{
										"$or": []bson.M{
											{"resourcenames": nil},
											{"resources": "*"},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		// $project stage
		{
			"$project": bson.M{
				"_id": 1,
			},
		},
	}
	cur, err := permissionSets.Aggregate(context.Background(), pipeline)
	if err != nil {
		return err
	}
	defer cur.Close(ctx)

	return adapter.MongoCursorHandler[roleBindGroup](ctx, cur, callback, complete)
}
