package edge

import (
	"context"
	"database/sql"
	"fmt"

	"github.com/DataDog/KubeHound/pkg/kubehound/graph/adapter"
	"github.com/DataDog/KubeHound/pkg/kubehound/graph/types"
	"github.com/DataDog/KubeHound/pkg/kubehound/models/converter"
	"github.com/DataDog/KubeHound/pkg/kubehound/models/store"
	"github.com/DataDog/KubeHound/pkg/kubehound/storage/storedb"
	gremlin "github.com/apache/tinkerpop/gremlin-go/v3/driver"
)

const (
	RoleBindCrbCrRName = "RoleBindClusteRoleBindingbClusterRoleRole"
)

func init() {
	Register(&RoleBindCrbCrR{}, RegisterDefault)
}

type RoleBindCrbCrR struct {
	BaseEdge
}

func (e *RoleBindCrbCrR) Label() string {
	return RoleBindLabel
}

func (e *RoleBindCrbCrR) Name() string {
	return RoleBindCrbCrRName
}

func (e *RoleBindCrbCrR) AttckTechniqueID() AttckTechniqueID {
	return AttckTechniqueValidAccounts
}

func (e *RoleBindCrbCrR) AttckTacticID() AttckTacticID {
	return AttckTacticPrivilegeEscalation
}

func (e *RoleBindCrbCrR) Processor(ctx context.Context, oic *converter.ObjectIDConverter, entry any) (any, error) {
	typed, ok := entry.(*roleBindGroup)
	if !ok {
		return nil, fmt.Errorf("invalid type passed to processor: %T", entry)
	}

	psid, err := oic.GraphID(ctx, store.Hex(typed.PermissionSet))
	if err != nil {
		return nil, fmt.Errorf("%s edge PermissionSet id convert: %w", e.Label(), err)
	}

	return psid, nil
}

func (e *RoleBindCrbCrR) Traversal() types.EdgeTraversal {
	return func(source *gremlin.GraphTraversalSource, inserts []any) *gremlin.GraphTraversal {
		g := source.GetGraphTraversal()

		if e.cfg.LargeClusterOptimizations {
			// For larger clusters simply target specific roles to reduce number of attack paths
			g.V().
				Has("runID", e.runtime.RunID.String()).
				Has("cluster", e.runtime.Cluster.Name).
				Has("class", "PermissionSet").
				Has("isNamespaced", true).
				// Temporary measure, until we scan and flag for sensitive roles
				Has("critical", true).
				// Has("role", P.Within(sensitiveRoles)).
				As("r").
				V(inserts...).
				Has("critical", false).
				AddE(e.Label()).
				To("r").
				Property("attckTechniqueID", string(e.AttckTechniqueID())).
				Property("attckTacticID", string(e.AttckTacticID())).
				Barrier().Limit(0)
		} else {
			// In smaller clusters we can still show the (large set of) attack paths generated by this attack
			g.V().
				Has("runID", e.runtime.RunID.String()).
				Has("cluster", e.runtime.Cluster.Name).
				Has("class", "PermissionSet").
				Has("isNamespaced", true).
				As("i").
				V(inserts...).
				Has("critical", false).
				AddE(e.Label()).
				To("i").
				Property("attckTechniqueID", string(e.AttckTechniqueID())).
				Property("attckTacticID", string(e.AttckTacticID())).
				Barrier().Limit(0)
		}

		return g
	}
}

func (e *RoleBindCrbCrR) Stream(ctx context.Context, _ storedb.Provider, db *sql.DB,
	callback types.ProcessEntryCallback, complete types.CompleteQueryCallback) error {

	rows, err := db.QueryContext(ctx, `
		SELECT DISTINCT ps.id
		FROM permissionsets ps
		JOIN rolebindings rb ON rb.id = ps.role_binding_id
			AND rb.run_id = ps.run_id
			AND rb.cluster_name = ps.cluster_name
		WHERE ps.is_namespaced = 0 AND rb.is_namespaced = 0
		AND ps.run_id = ? AND ps.cluster_name = ?
		AND EXISTS (
			SELECT 1 FROM json_each(ps.rules) AS r1
			WHERE EXISTS (SELECT 1 FROM json_each(json_extract(r1.value, '$.apiGroups')) WHERE value IN ('*', 'rbac.authorization.k8s.io'))
		)
		AND EXISTS (
			SELECT 1 FROM json_each(ps.rules) AS r2
			WHERE EXISTS (SELECT 1 FROM json_each(json_extract(r2.value, '$.verbs')) WHERE value IN ('create', '*'))
			AND EXISTS (SELECT 1 FROM json_each(json_extract(r2.value, '$.resources')) WHERE value IN ('rolebindings', '*'))
			AND (json_extract(r2.value, '$.resourceNames') IS NULL OR json_extract(r2.value, '$.resourceNames') = '[]')
		)
		AND EXISTS (
			SELECT 1 FROM json_each(ps.rules) AS r3
			WHERE EXISTS (SELECT 1 FROM json_each(json_extract(r3.value, '$.verbs')) WHERE value IN ('bind', '*'))
			AND EXISTS (SELECT 1 FROM json_each(json_extract(r3.value, '$.resources')) WHERE value IN ('roles', '*'))
			AND (json_extract(r3.value, '$.resourceNames') IS NULL OR json_extract(r3.value, '$.resourceNames') = '[]')
		)`,
		e.runtime.RunID.String(), e.runtime.Cluster.Name)
	if err != nil {
		return err
	}

	return adapter.SQLiteRowHandler[roleBindGroup](ctx, rows, func(row *sql.Rows) (roleBindGroup, error) {
		var g roleBindGroup
		err := row.Scan(&g.PermissionSet)
		return g, err
	}, callback, complete)
}
