package edge

import (
	"context"
	"fmt"

	"github.com/DataDog/KubeHound/pkg/kubehound/graph/adapter"
	"github.com/DataDog/KubeHound/pkg/kubehound/graph/types"
	"github.com/DataDog/KubeHound/pkg/kubehound/models/converter"
	"github.com/DataDog/KubeHound/pkg/kubehound/storage/cache"
	"github.com/DataDog/KubeHound/pkg/kubehound/storage/storedb"
	"github.com/DataDog/KubeHound/pkg/kubehound/store/collections"
	gremlin "github.com/apache/tinkerpop/gremlin-go/v3/driver"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
)

const (
	RoleBindLabel = "ROLE_BIND"
	RoleBindName  = "RoleBind"
)

// Default Kubernetes roles with high privileges
var sensitiveRoles = []string{"cluster-admin", "admin", "system:kubelet-api-admin", "system:node"}

func init() {
	Register(&RoleBind{}, RegisterDefault)
}

// @@DOCLINK: https://datadoghq.atlassian.net/wiki/spaces/ASE/pages/2889355675/ROLE+BIND
type RoleBind struct {
	BaseEdge
}

type roleBindGroup struct {
	Role primitive.ObjectID `bson:"_id" json:"role"`
}

func (e *RoleBind) Label() string {
	return RoleBindLabel
}

func (e *RoleBind) Name() string {
	return RoleBindName
}

func (e *RoleBind) Processor(ctx context.Context, oic *converter.ObjectIDConverter, entry any) (any, error) {
	typed, ok := entry.(*roleBindGroup)
	if !ok {
		return nil, fmt.Errorf("invalid type passed to processor: %T", entry)
	}

	rid, err := oic.GraphID(ctx, typed.Role.Hex())
	if err != nil {
		return nil, fmt.Errorf("%s edge role id convert: %w", e.Label(), err)
	}

	return rid, nil
}

func (e *RoleBind) Traversal() types.EdgeTraversal {
	return func(source *gremlin.GraphTraversalSource, inserts []any) *gremlin.GraphTraversal {
		g := source.GetGraphTraversal()
		if e.cfg.LargeClusterOptimizations {
			// For larger clusters simply target specific roles to reduce number of attack paths
			g.V().
				HasLabel("Role").
				// Temporary measure, until we scan and flag for sensitive roles
				Has("name", P.Within(sensitiveRoles)).
				As("r").
				V(inserts...).
				Has("critical", false).
				AddE(e.Label()).
				To("r").
				Barrier().Limit(0)
		} else {
			// In smaller clusters we can still show the (large set of) attack paths generated by this attack
			g.V().
				HasLabel("Role").
				Has("class", "Role").
				As("i").
				V(inserts...).
				Has("critical", false).
				AddE(e.Label()).
				To("i").
				Barrier().Limit(0)
		}

		return g
	}
}

func (e *RoleBind) Stream(ctx context.Context, store storedb.Provider, c cache.CacheReader,
	callback types.ProcessEntryCallback, complete types.CompleteQueryCallback) error {

	roleBindings := adapter.MongoDB(store).Collection(collections.RoleName)
	pipeline := []bson.M{
		// $match stage
		{
			"$match": bson.M{
				"is_namespaced": false,
				"rules": bson.M{
					"$elemMatch": bson.M{
						"$or": []bson.M{
							{"apigroups": "*"},
							{"apigroups": "rbac.authorization.k8s.io"},
						},
					},
				},
				"$and": []bson.M{
					{
						"rules": bson.M{
							"$elemMatch": bson.M{
								"$and": []bson.M{
									{
										"$or": []bson.M{
											{"verbs": "create"},
											{"verbs": "*"},
										},
									},
									{
										"$or": []bson.M{
											{"resources": "rolebindings"},
											{"resources": "*"},
										},
									},
								},
							},
						},
					},
					{
						"rules": bson.M{
							"$elemMatch": bson.M{
								"$and": []bson.M{
									{
										"$or": []bson.M{
											{"verbs": "bind"},
											{"verbs": "*"},
										},
									},
									{
										"$or": []bson.M{
											{"resources": "clusterrolebindings"},
											{"resources": "clusterroles"},
											{"resources": "*"},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		// $project stage
		{
			"$project": bson.M{
				"_id": 1,
			},
		},
	}
	cur, err := roleBindings.Aggregate(context.Background(), pipeline)
	if err != nil {
		return err
	}
	defer cur.Close(ctx)

	return adapter.MongoCursorHandler[roleBindGroup](ctx, cur, callback, complete)
}
