from gcr.io/datadoghq/agent:7-jmx

ADD datadog.yaml /etc/datadog-agent/datadog.yaml
ADD mongodb.yaml /etc/datadog-agent/conf.d/mongo.d/conf.yaml
ADD openmetrics.yaml /etc/datadog-agent/conf.d/openmetrics.d/conf.yaml