version: "3.8"
name: kubehound-prod
services:
  mongodb:
    volumes:
      - mongodb_data:/data/db

  janusgraph:
    image: ghcr.io/datadog/kubehound/kubehound-janusgraph:latest
    volumes:
      - janusgraph_data:/data
    environment:
      # Enforce strict schema constrains as per https://docs.janusgraph.org/configs/configuration-reference/#schema
      - janusgraph.schema.constraints=true
      - janusgraph.schema.default=none
      # Bump content length of web-socket buffer to enable bulk insert queries
      - gremlinserver.maxContentLength=2097152
      # Bump evaluation timeout to support our large datasets
      - gremlinserver.evaluationTimeout=60000

  kubehound:
    container_name: ${COMPOSE_PROJECT_NAME}-core
    profiles: ["core"]
    restart: unless-stopped
    image: ghcr.io/datadog/kubehound/kubehound-core:latest
    environment:
      - KUBECONFIG=/tmp/.kube/config
    volumes:
      - ./.kube-config:/tmp/.kube/config
    networks:
      - kubenet

volumes:
  mongodb_data:
  janusgraph_data: