version: "3.8"
name: kubehound-testing
services:
  mongodb:
    ports:
      - "127.0.0.1:27018:27017"
  kubegraph:
    build: ./kubegraph/
    ports:
      - "127.0.0.1:8183:8182"
networks:
  kind:
    external: true