services:
  notebook:
    build: ./notebook/
    restart: unless-stopped
    ports:
      - "127.0.0.1:8888:8888"
    networks:
      - kubenet
    volumes:
      - ./notebook/shared:/root/notebooks/shared

networks:
  kubenet: