name: kubehound-release
services:
  grpc:
    image: ghcr.io/datadog/kubehound-binary:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:9000:9000"
    networks:
      - kubenet
    env_file:
      - kubehound.env

networks:
  kubenet:
