version: "3.8"
name: kubehound-prod
services:
  mongodb:
    volumes:
      - mongodb_data:/data/db

  janusgraph:
    image: ghcr.io/datadog/kubehound/kubehound-janusgraph:latest
    volumes:
      - janusgraph_data:/var/lib/janusgraph

  kubehound:
    container_name: ${COMPOSE_PROJECT_NAME}-core
    profiles: ["core"]
    restart: unless-stopped
    image: ghcr.io/datadog/kubehound/kubehound-core:latest
    environment:
      - KUBECONFIG=/tmp/.kube/config
    volumes:
      - ./.kube-config:/tmp/.kube/config
    networks:
      - kubenet

volumes:
  mongodb_data:
  janusgraph_data: