version: "3.7"

services:
  mongodb:
    image: mongo
    container_name: storedb
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongodb
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/

  janusgraph:
    image: janusgraph/janusgraph:latest
    container_name: graphdb-ng
    ports:
      - "8182:8182"
    volumes:
      - ./data/janus:/data