version: "3.8"
name: kubehound-prod
services:
  mongodb:
    volumes:
      - mongodb_data:/data/db

  janusgraph:
    image: ghcr.io/datadog/kubehound/kubehound-graph:latest
    volumes:
      - janusgraph_data:/var/lib/janusgraph

volumes:
  mongodb_data:
  janusgraph_data: