version: "3.8"
name: kubehound-release
services:
  mongodb:
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongodb_data:/data/db

  janusgraph:
    ports:
      - "127.0.0.1:8182:8182"
      - "127.0.0.1:8099:8099"
    volumes:
      - janusgraph_data:/var/lib/janusgraph

volumes:
  mongodb_data:
  janusgraph_data:

networks:
  kind:
    external: true