version: "3.8"
services:
  datadog:
    image: gcr.io/datadoghq/agent:7-jmx
    restart: unless-stopped
    profiles: ["infra"]
    container_name: ${COMPOSE_PROJECT_NAME}-datadog-agent
    ports:
      - "127.0.0.1:8225:8125/UDP"
      - "127.0.0.1:8226:8126"
    environment:
      - DD_API_KEY=${DD_API_KEY:?error}
      - DD_HOSTNAME=${DOCKER_HOSTNAME:?error}
      - DD_ENV=${KUBEHOUND_ENV:-dev}
      - DD_TAGS="service:kubehound"
      - DD_APM_ENABLED=true
      - DD_LOGS_ENABLED=true
      - DD_PROCESS_AGENT_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_CONTAINER_LABELS_AS_TAGS={"com.docker.compose.service":"+app"}
      - DD_CONTAINER_INCLUDE=name:kubehound-*
      # https://github.com/DataDog/datadog-agent/issues/6599
      - DD_CONTAINER_EXCLUDE=name:kubehound-dev-mongo-express
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./datadog/datadog.yaml:/etc/datadog-agent/datadog.yaml:ro
      - ./datadog/mongodb.yaml:/etc/datadog-agent/conf.d/mongo.d/conf.yaml:ro
      - ./datadog/openmetrics.yaml:/etc/datadog-agent/conf.d/openmetrics.d/conf.yaml:ro
    networks:
      - kubenet

networks:
  kubenet: