// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"

	types "github.com/DataDog/KubeHound/pkg/globals/types"
	mock "github.com/stretchr/testify/mock"
)

// ClusterRoleIngestor is an autogenerated mock type for the ClusterRoleIngestor type
type ClusterRoleIngestor struct {
	mock.Mock
}

type ClusterRoleIngestor_Expecter struct {
	mock *mock.Mock
}

func (_m *ClusterRoleIngestor) EXPECT() *ClusterRoleIngestor_Expecter {
	return &ClusterRoleIngestor_Expecter{mock: &_m.Mock}
}

// Complete provides a mock function with given fields: _a0
func (_m *ClusterRoleIngestor) Complete(_a0 context.Context) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ClusterRoleIngestor_Complete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Complete'
type ClusterRoleIngestor_Complete_Call struct {
	*mock.Call
}

// Complete is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *ClusterRoleIngestor_Expecter) Complete(_a0 interface{}) *ClusterRoleIngestor_Complete_Call {
	return &ClusterRoleIngestor_Complete_Call{Call: _e.mock.On("Complete", _a0)}
}

func (_c *ClusterRoleIngestor_Complete_Call) Run(run func(_a0 context.Context)) *ClusterRoleIngestor_Complete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *ClusterRoleIngestor_Complete_Call) Return(_a0 error) *ClusterRoleIngestor_Complete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ClusterRoleIngestor_Complete_Call) RunAndReturn(run func(context.Context) error) *ClusterRoleIngestor_Complete_Call {
	_c.Call.Return(run)
	return _c
}

// IngestClusterRole provides a mock function with given fields: _a0, _a1
func (_m *ClusterRoleIngestor) IngestClusterRole(_a0 context.Context, _a1 types.ClusterRoleType) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.ClusterRoleType) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ClusterRoleIngestor_IngestClusterRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IngestClusterRole'
type ClusterRoleIngestor_IngestClusterRole_Call struct {
	*mock.Call
}

// IngestClusterRole is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 types.ClusterRoleType
func (_e *ClusterRoleIngestor_Expecter) IngestClusterRole(_a0 interface{}, _a1 interface{}) *ClusterRoleIngestor_IngestClusterRole_Call {
	return &ClusterRoleIngestor_IngestClusterRole_Call{Call: _e.mock.On("IngestClusterRole", _a0, _a1)}
}

func (_c *ClusterRoleIngestor_IngestClusterRole_Call) Run(run func(_a0 context.Context, _a1 types.ClusterRoleType)) *ClusterRoleIngestor_IngestClusterRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(types.ClusterRoleType))
	})
	return _c
}

func (_c *ClusterRoleIngestor_IngestClusterRole_Call) Return(_a0 error) *ClusterRoleIngestor_IngestClusterRole_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ClusterRoleIngestor_IngestClusterRole_Call) RunAndReturn(run func(context.Context, types.ClusterRoleType) error) *ClusterRoleIngestor_IngestClusterRole_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewClusterRoleIngestor interface {
	mock.TestingT
	Cleanup(func())
}

// NewClusterRoleIngestor creates a new instance of ClusterRoleIngestor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewClusterRoleIngestor(t mockConstructorTestingTNewClusterRoleIngestor) *ClusterRoleIngestor {
	mock := &ClusterRoleIngestor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
