name: build-kubehound-images

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: datadog/kubehound

permissions:
  contents: read

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    strategy:
      # https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
      matrix:
        include:
          - dockerfile: deployments/kubehound/graph/Dockerfile
            image: graph
            workdir: deployments/kubehound/graph/
          - dockerfile: deployments/kubehound/ui/Dockerfile
            image: ui
            workdir: deployments/kubehound/ui/
          - dockerfile: deployments/kubehound/binary/Dockerfile
            image: binary
            workdir: .
    permissions:
      contents: read
      packages: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          # egress-policy: audit
          egress-policy: block
          allowed-endpoints: >
            auth.docker.io:443
            dl-cdn.alpinelinux.org:443
            ghcr.io:443
            github.com:443
            pipelines.actions.githubusercontent.com:443
            pkg-containers.githubusercontent.com:443
            production.cloudflare.docker.com:443
            proxy.golang.org:443
            storage.googleapis.com:443
            *.docker.io:443
            *.docker.com:443
            gcr.io:443
            repo.maven.apache.org:443
            amazonlinux.default.amazonaws.com:443
            amazonlinux.default.amazonaws.com:80
            cdn.amazonlinux.com:443
            rpm.nodesource.com:443
            registry.npmjs.org:443
            pypi.org:443
            *.pypi.org:443
            api.snapcraft.io:443
            files.pythonhosted.org:443
            acghubeus1.actions.githubusercontent.com:443
            pipelinesghubeus8.actions.githubusercontent.com:443
            productionresultssa8.blob.core.windows.net:443
            results-receiver.actions.githubusercontent.com:443
            vstsmms.actions.githubusercontent.com:443
            raw.githubusercontent.com:443
            nodejs.org:443
            iojs.org:443

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5 # v3.8.0

      - name: Build and push Docker image
        if: ${{ github.event_name == 'push' }}
        uses: docker/build-push-action@48aba3b46d1b1fec4febb7c5d0c644b249a11355 # v6.10.0
        with:
          context: ${{ matrix.workdir }}
          platforms: linux/amd64,linux/arm64
          file: ${{ matrix.dockerfile }}
          push: true
          build-args: |
            VERSION=${{ github.ref_name }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ matrix.image }}:${{ github.ref_name }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ matrix.image }}:latest

      - name: Build and push Docker image
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: docker/build-push-action@48aba3b46d1b1fec4febb7c5d0c644b249a11355 # v6.10.0
        with:
          context: ${{ matrix.workdir }}
          platforms: linux/amd64,linux/arm64
          file: ${{ matrix.dockerfile }}
          push: true
          build-args: |
            VERSION=${{ github.sha }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ matrix.image }}:snapshot-${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ matrix.image }}:latest
