name: generate-docs
on:
  workflow_dispatch: {} # allow manually triggering the workflow
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - mkdocs.yml

permissions:
  contents: read

jobs:
  deploy:
    permissions:
      contents: write  # for mkdocs gh-deploy to publish docs
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: block
          allowed-endpoints: >
            files.pythonhosted.org:443
            github.com:443
            pypi.org:443

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mkdocs-awesome-pages-plugin markdown-captions
      - run: mkdocs gh-deploy --force
