name: generate-docs
on:
  workflow_dispatch: {} # allow manually triggering the workflow
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - mkdocs.yml

permissions:
  contents: read

jobs:
  deploy:
    permissions:
      contents: write  # for mkdocs gh-deploy to publish docs
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@cba0d00b1fc9a034e1e642ea0f1103c282990604
        with:
          egress-policy: block
          allowed-endpoints: >
            files.pythonhosted.org:443
            github.com:443
            pypi.org:443

      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      - uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mkdocs-awesome-pages-plugin markdown-captions
      - run: mkdocs gh-deploy --force