name: kubehound-golang-lint

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  # from their official doc: https://github.com/golangci/golangci-lint-action
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: harden-runner
        uses: step-security/harden-runner@6b3083af2869dc3314a0257a42f4af696cc79ba3
        with:
          egress-policy: block
          allowed-endpoints:
            api.github.com:443
            github.com:443
            proxy.golang.org:443
            golang.org:443
            go.dev:443
            storage.googleapis.com:443

      - name: setup-golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: git-repo-checkout
        uses: actions/checkout@v3

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.50
          working-directory: ./
