name: kubehound-golang-lint

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  # from their official doc: https://github.com/golangci/golangci-lint-action
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.20
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.50
          working-directory: ./
