name: kubehound-system-tests

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read # to fetch code (actions/checkout)
  id-token: write

jobs:
  system-test:
    runs-on:
      group: Large Runner Shared Public
      labels: ubuntu-8-core-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            goreleaser.com:443
            golang.org:443
            go.dev:443
            objects.githubusercontent.com:443
            proxy.golang.org:443
            storage.googleapis.com:443
            uploads.github.com:443
            sum.golang.org:443
            *.docker.io:443
            *.docker.com:443
            gcr.io:443
            repo.maven.apache.org:443
            *.datadoghq.com:443
            dl.k8s.io:443
            cdn.dl.k8s.io:443

      - name: Checkout Git Repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Get Datadog credentials
        id: dd-sts
        uses: DataDog/dd-sts-action@main
        with:
          policy: kubehound-system-test

      - name: Start Datadog Agent
        if: ${{ ! github.event.pull_request.head.repo.fork }}
        run: |
          docker run -d \
            --name dd-agent \
            --network host \
            -e DD_API_KEY="${{ steps.dd-sts.outputs.api_key }}" \
            -e DD_TRACE_DEBUG=1 \
            -e DD_LOGS_ENABLED=true \
            -e DD_APM_ENABLED=true \
            -e DD_HOSTNAME="kubehound-github-action" \
            gcr.io/datadoghq/agent:7

          echo "Waiting for DD agent to be ready..."
          for i in {1..30}; do
            if curl -sf http://localhost:8126/info > /dev/null 2>&1; then
              echo "DD agent is ready!"
              break
            fi
            echo "Waiting for DD agent... ($i/30)"
            sleep 2
          done

      - name: Create K8s Kind Cluster
        uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0
        with:
          cluster_name: kubehound.test.local
          config: test/setup/test-cluster/cluster.yaml
          wait: 5m
        env:
          KUBECONFIG: ./test/setup/.kube-config

      - name: Create K8s resources
        run: make local-cluster-resource-deploy
        env:
          KUBECONFIG: ./test/setup/.kube-config

      - name: Setup Golang
        uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version: "1.24"

      - name: Run integration Tests
        run: make system-test
        env:
          KIND_KUBECONFIG: .kube-config
