name: kubehound-system-tests

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  system-test:
    runs-on:
      group: Large Runner Shared Public
      labels: ubuntu-8-core-latest
    services:
      dd-agent:
        image: ${{ (! github.event.pull_request.head.repo.fork ) && 'gcr.io/datadoghq/agent:7' || '' }}
        env:
          DD_API_KEY: ${{ secrets.DD_API_KEY }}
          DD_TRACE_DEBUG: 1
          DD_LOGS_ENABLED: true
          DD_APM_ENABLED: true
          DD_HOSTNAME: "kubehound-github-action"
        ports:
          - 8126:8126
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            goreleaser.com:443
            golang.org:443
            go.dev:443
            objects.githubusercontent.com:443
            proxy.golang.org:443
            storage.googleapis.com:443
            uploads.github.com:443
            sum.golang.org:443
            *.docker.io:443
            *.docker.com:443
            gcr.io:443
            repo.maven.apache.org:443
            *.datadoghq.com:443

      - name: Checkout Git Repo
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

      - name: Create K8s Kind Cluster
        uses: helm/kind-action@9e8295d178de23cbfbd8fa16cf844eec1d773a07
        with:
          cluster_name: kubehound.test.local
          config: test/setup/test-cluster/cluster.yaml
          wait: 5m
        env:
          KUBECONFIG: ./test/setup/.kube-config

      - name: Create K8s resources
        run: make local-cluster-resource-deploy
        env:
          KUBECONFIG: ./test/setup/.kube-config

      - name: Setup Golang
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe
        with:
          go-version: "1.22"

      - name: Run integration Tests
        run: make system-test
        env:
          KIND_KUBECONFIG: .kube-config
