name: KubeHound System Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  system-test:
    runs-on: ubuntu-latest
    environment: devenv
    steps:
      - uses: datadog/agent-github-action@v1.3
        with:
          api_key: ${{ secrets.DD_API_KEY }}

      - name: Checkout Git Repo
        uses: actions/checkout@v3

      - name: Create K8s Kind Cluster
        uses: helm/kind-action@v1.4.0
        with:
          cluster_name: kubehound.test.local
          config: test/setup/test-cluster/cluster.yaml
          wait: 5m

      - name: Create K8s resources
        working-directory: test/setup/
        run: bash create-cluster-resources.sh
      
      - name: Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Run integration Tests
        run: make system-test