name: test-extract

permissions:
  contents: read

on:
  pull_request:

jobs:
  extract:
    name: Try to extract secrets
    runs-on: ubuntu-latest
    steps:
      - name: Extract test secret
        run: echo -n ${{ secrets.DD_FAKE_NO_INCIDENT_PLS }} | sha256sum
      - name: Extract test secret with env var
        env:
          TEST_SEC: ${{ secrets.DD_FAKE_INCIDENT_PLS }}
        run: echo -n $TEST_SEC | sha256sum
      - name: Echo secret directly
        run: echo ${{ secrets.DD_FAKE_NO_INCIDENT_PLS }}
