// PLEASE DO NOT EDIT
// THIS HAS BEEN GENERATED AUTOMATICALLY on 2023-09-19 16:41
//
// Generate it with "go generate ./..."
//
// currently support only:
// - nodes
// - pods
// - containers
// - volumes
//
// TODO: roles, rolebinding, clusterrole, clusterrolebindings

package system

import (
	"github.com/DataDog/KubeHound/pkg/kubehound/models/graph"
	"github.com/DataDog/KubeHound/pkg/kubehound/models/shared"
)

var expectedPods = map[string]graph.Pod{
	"control-pod": {
		StoreID:               "",
		Name:                  "control-pod",
		IsNamespaced:          true,
		Namespace:             "default",
		Compromised:           shared.CompromiseNone,
		ServiceAccount:        "default",
		ShareProcessNamespace: false,
		Critical:              false,
	},
	"endpoints-pod": {
		StoreID:               "",
		Name:                  "endpoints-pod",
		IsNamespaced:          true,
		Namespace:             "default",
		Compromised:           shared.CompromiseNone,
		ServiceAccount:        "default",
		ShareProcessNamespace: false,
		Critical:              false,
	},
	"host-read-exploit-pod": {
		StoreID:               "",
		Name:                  "host-read-exploit-pod",
		IsNamespaced:          true,
		Namespace:             "default",
		Compromised:           shared.CompromiseNone,
		ServiceAccount:        "default",
		ShareProcessNamespace: false,
		Critical:              false,
	},
	"host-write-exploit-pod": {
		StoreID:               "",
		Name:                  "host-write-exploit-pod",
		IsNamespaced:          true,
		Namespace:             "default",
		Compromised:           shared.CompromiseNone,
		ServiceAccount:        "default",
		ShareProcessNamespace: false,
		Critical:              false,
	},
	"impersonate-pod": {
		StoreID:               "",
		Name:                  "impersonate-pod",
		IsNamespaced:          true,
		Namespace:             "default",
		Compromised:           shared.CompromiseNone,
		ServiceAccount:        "impersonate-sa",
		ShareProcessNamespace: false,
		Critical:              false,
	},
	"modload-pod": {
		StoreID:               "",
		Name:                  "modload-pod",
		IsNamespaced:          true,
		Namespace:             "default",
		Compromised:           shared.CompromiseNone,
		ServiceAccount:        "default",
		ShareProcessNamespace: false,
		Critical:              false,
	},
	"netadmin-pod": {
		StoreID:               "",
		Name:                  "netadmin-pod",
		IsNamespaced:          true,
		Namespace:             "default",
		Compromised:           shared.CompromiseNone,
		ServiceAccount:        "default",
		ShareProcessNamespace: false,
		Critical:              false,
	},
	"nsenter-pod": {
		StoreID:               "",
		Name:                  "nsenter-pod",
		IsNamespaced:          true,
		Namespace:             "default",
		Compromised:           shared.CompromiseNone,
		ServiceAccount:        "default",
		ShareProcessNamespace: false,
		Critical:              false,
	},
	"pod-create-pod": {
		StoreID:               "",
		Name:                  "pod-create-pod",
		IsNamespaced:          true,
		Namespace:             "default",
		Compromised:           shared.CompromiseNone,
		ServiceAccount:        "pod-create-sa",
		ShareProcessNamespace: false,
		Critical:              false,
	},
	"pod-exec-pod": {
		StoreID:               "",
		Name:                  "pod-exec-pod",
		IsNamespaced:          true,
		Namespace:             "default",
		Compromised:           shared.CompromiseNone,
		ServiceAccount:        "pod-exec-sa",
		ShareProcessNamespace: false,
		Critical:              false,
	},
	"pod-patch-pod": {
		StoreID:               "",
		Name:                  "pod-patch-pod",
		IsNamespaced:          true,
		Namespace:             "default",
		Compromised:           shared.CompromiseNone,
		ServiceAccount:        "pod-patch-sa",
		ShareProcessNamespace: false,
		Critical:              false,
	},
	"priv-pod": {
		StoreID:               "",
		Name:                  "priv-pod",
		IsNamespaced:          true,
		Namespace:             "default",
		Compromised:           shared.CompromiseNone,
		ServiceAccount:        "default",
		ShareProcessNamespace: false,
		Critical:              false,
	},
	"rolebind-pod": {
		StoreID:               "",
		Name:                  "rolebind-pod",
		IsNamespaced:          true,
		Namespace:             "default",
		Compromised:           shared.CompromiseNone,
		ServiceAccount:        "rolebind-sa",
		ShareProcessNamespace: false,
		Critical:              false,
	},
	"sharedps-pod1": {
		StoreID:               "",
		Name:                  "sharedps-pod1",
		IsNamespaced:          true,
		Namespace:             "default",
		Compromised:           shared.CompromiseNone,
		ServiceAccount:        "default",
		ShareProcessNamespace: true,
		Critical:              false,
	},
	"sharedps-pod2": {
		StoreID:               "",
		Name:                  "sharedps-pod2",
		IsNamespaced:          true,
		Namespace:             "default",
		Compromised:           shared.CompromiseNone,
		ServiceAccount:        "default",
		ShareProcessNamespace: true,
		Critical:              false,
	},
	"sys-ptrace-pod": {
		StoreID:               "",
		Name:                  "sys-ptrace-pod",
		IsNamespaced:          true,
		Namespace:             "default",
		Compromised:           shared.CompromiseNone,
		ServiceAccount:        "default",
		ShareProcessNamespace: false,
		Critical:              false,
	},
	"tokenget-pod": {
		StoreID:               "",
		Name:                  "tokenget-pod",
		IsNamespaced:          true,
		Namespace:             "default",
		Compromised:           shared.CompromiseNone,
		ServiceAccount:        "tokenget-sa",
		ShareProcessNamespace: false,
		Critical:              false,
	},
	"tokenlist-pod": {
		StoreID:               "",
		Name:                  "tokenlist-pod",
		IsNamespaced:          true,
		Namespace:             "default",
		Compromised:           shared.CompromiseNone,
		ServiceAccount:        "tokenlist-sa",
		ShareProcessNamespace: false,
		Critical:              false,
	},
	"umh-core-pod": {
		StoreID:               "",
		Name:                  "umh-core-pod",
		IsNamespaced:          true,
		Namespace:             "default",
		Compromised:           shared.CompromiseNone,
		ServiceAccount:        "default",
		ShareProcessNamespace: false,
		Critical:              false,
	},
	"varlog-pod": {
		StoreID:               "",
		Name:                  "varlog-pod",
		IsNamespaced:          true,
		Namespace:             "default",
		Compromised:           shared.CompromiseNone,
		ServiceAccount:        "varlog-sa",
		ShareProcessNamespace: false,
		Critical:              false,
	},
}

var expectedNodes = map[string]graph.Node{
	"kubehound.test.local-control-plane": {
		StoreID:      "",
		Name:         "kubehound.test.local-control-plane",
		IsNamespaced: false,
		Namespace:    "",
		Compromised:  shared.CompromiseNone,
		Critical:     false,
	},
	"kubehound.test.local-worker": {
		StoreID:      "",
		Name:         "kubehound.test.local-worker",
		IsNamespaced: false,
		Namespace:    "",
		Compromised:  shared.CompromiseNone,
		Critical:     false,
	},
	"kubehound.test.local-worker2": {
		StoreID:      "",
		Name:         "kubehound.test.local-worker2",
		IsNamespaced: false,
		Namespace:    "",
		Compromised:  shared.CompromiseNone,
		Critical:     false,
	},
}

var expectedVolumes = map[string]graph.Volume{
	"host-pod-dir": {
		StoreID:    "",
		Name:       "host-pod-dir",
		Type:       "",
		SourcePath: "",
		MountPath:  "/hostpods/",
		Readonly:   true,
	},
	"host-ssh": {
		StoreID:    "",
		Name:       "host-ssh",
		Type:       "",
		SourcePath: "",
		MountPath:  "/hostssh/",
		Readonly:   true,
	},
	"hostroot": {
		StoreID:    "",
		Name:       "hostroot",
		Type:       "",
		SourcePath: "",
		MountPath:  "/host/",
		Readonly:   false,
	},
	"nodelog": {
		StoreID:    "",
		Name:       "nodelog",
		Type:       "",
		SourcePath: "",
		MountPath:  "/host/var/log",
		Readonly:   false,
	},
	"nodeproc": {
		StoreID:    "",
		Name:       "nodeproc",
		Type:       "",
		SourcePath: "",
		MountPath:  "/sysproc",
		Readonly:   false,
	},
}

var expectedContainers = map[string]graph.Container{
	"control-pod": {
		StoreID:      "",
		Name:         "control-pod",
		Image:        "ubuntu",
		Command:      []string{},
		Args:         []string{},
		Capabilities: []string{},
		Privileged:   false,
		PrivEsc:      false,
		HostPID:      false,
		HostIPC:      false,
		HostNetwork:  false,
		RunAsUser:    0,
		Ports:        []string{},
		Pod:          "control-pod",
		// Node:         "",
		Compromised: 0,
	},
	"endpoints-pod": {
		StoreID:      "",
		Name:         "endpoints-pod",
		Image:        "ubuntu",
		Command:      []string{},
		Args:         []string{},
		Capabilities: []string{},
		Privileged:   true,
		PrivEsc:      false,
		HostPID:      false,
		HostIPC:      false,
		HostNetwork:  false,
		RunAsUser:    0,
		Ports:        []string{},
		Pod:          "endpoints-pod",
		// Node:         "",
		Compromised: 0,
	},
	"host-read-exploit-pod": {
		StoreID:      "",
		Name:         "host-read-exploit-pod",
		Image:        "ubuntu",
		Command:      []string{},
		Args:         []string{},
		Capabilities: []string{},
		Privileged:   false,
		PrivEsc:      false,
		HostPID:      false,
		HostIPC:      false,
		HostNetwork:  false,
		RunAsUser:    0,
		Ports:        []string{},
		Pod:          "host-read-exploit-pod",
		// Node:         "",
		Compromised: 0,
	},
	"host-write-exploit-pod": {
		StoreID:      "",
		Name:         "host-write-exploit-pod",
		Image:        "ubuntu",
		Command:      []string{},
		Args:         []string{},
		Capabilities: []string{},
		Privileged:   false,
		PrivEsc:      false,
		HostPID:      false,
		HostIPC:      false,
		HostNetwork:  false,
		RunAsUser:    0,
		Ports:        []string{},
		Pod:          "host-write-exploit-pod",
		// Node:         "",
		Compromised: 0,
	},
	"impersonate-pod": {
		StoreID:      "",
		Name:         "impersonate-pod",
		Image:        "ubuntu",
		Command:      []string{},
		Args:         []string{},
		Capabilities: []string{},
		Privileged:   false,
		PrivEsc:      false,
		HostPID:      false,
		HostIPC:      false,
		HostNetwork:  false,
		RunAsUser:    0,
		Ports:        []string{},
		Pod:          "impersonate-pod",
		// Node:         "",
		Compromised: 0,
	},
	"modload-pod": {
		StoreID:      "",
		Name:         "modload-pod",
		Image:        "ubuntu",
		Command:      []string{},
		Args:         []string{},
		Capabilities: []string{},
		Privileged:   false,
		PrivEsc:      false,
		HostPID:      false,
		HostIPC:      false,
		HostNetwork:  false,
		RunAsUser:    0,
		Ports:        []string{},
		Pod:          "modload-pod",
		// Node:         "",
		Compromised: 0,
	},
	"netadmin-pod": {
		StoreID:      "",
		Name:         "netadmin-pod",
		Image:        "ubuntu",
		Command:      []string{},
		Args:         []string{},
		Capabilities: []string{},
		Privileged:   false,
		PrivEsc:      false,
		HostPID:      false,
		HostIPC:      false,
		HostNetwork:  false,
		RunAsUser:    0,
		Ports:        []string{},
		Pod:          "netadmin-pod",
		// Node:         "",
		Compromised: 0,
	},
	"nsenter-pod": {
		StoreID:      "",
		Name:         "nsenter-pod",
		Image:        "ubuntu",
		Command:      []string{},
		Args:         []string{},
		Capabilities: []string{},
		Privileged:   true,
		PrivEsc:      false,
		HostPID:      false,
		HostIPC:      false,
		HostNetwork:  false,
		RunAsUser:    0,
		Ports:        []string{},
		Pod:          "nsenter-pod",
		// Node:         "",
		Compromised: 0,
	},
	"pod-create-pod": {
		StoreID:      "",
		Name:         "pod-create-pod",
		Image:        "ubuntu",
		Command:      []string{},
		Args:         []string{},
		Capabilities: []string{},
		Privileged:   false,
		PrivEsc:      false,
		HostPID:      false,
		HostIPC:      false,
		HostNetwork:  false,
		RunAsUser:    0,
		Ports:        []string{},
		Pod:          "pod-create-pod",
		// Node:         "",
		Compromised: 0,
	},
	"pod-exec-pod": {
		StoreID:      "",
		Name:         "pod-exec-pod",
		Image:        "ubuntu",
		Command:      []string{},
		Args:         []string{},
		Capabilities: []string{},
		Privileged:   false,
		PrivEsc:      false,
		HostPID:      false,
		HostIPC:      false,
		HostNetwork:  false,
		RunAsUser:    0,
		Ports:        []string{},
		Pod:          "pod-exec-pod",
		// Node:         "",
		Compromised: 0,
	},
	"pod-patch-pod": {
		StoreID:      "",
		Name:         "pod-patch-pod",
		Image:        "ubuntu",
		Command:      []string{},
		Args:         []string{},
		Capabilities: []string{},
		Privileged:   false,
		PrivEsc:      false,
		HostPID:      false,
		HostIPC:      false,
		HostNetwork:  false,
		RunAsUser:    0,
		Ports:        []string{},
		Pod:          "pod-patch-pod",
		// Node:         "",
		Compromised: 0,
	},
	"priv-pod": {
		StoreID:      "",
		Name:         "priv-pod",
		Image:        "ubuntu",
		Command:      []string{},
		Args:         []string{},
		Capabilities: []string{},
		Privileged:   true,
		PrivEsc:      false,
		HostPID:      false,
		HostIPC:      false,
		HostNetwork:  false,
		RunAsUser:    0,
		Ports:        []string{},
		Pod:          "priv-pod",
		// Node:         "",
		Compromised: 0,
	},
	"rolebind-pod": {
		StoreID:      "",
		Name:         "rolebind-pod",
		Image:        "ubuntu",
		Command:      []string{},
		Args:         []string{},
		Capabilities: []string{},
		Privileged:   false,
		PrivEsc:      false,
		HostPID:      false,
		HostIPC:      false,
		HostNetwork:  false,
		RunAsUser:    0,
		Ports:        []string{},
		Pod:          "rolebind-pod",
		// Node:         "",
		Compromised: 0,
	},
	"sharedps-pod-a": {
		StoreID:      "",
		Name:         "sharedps-pod-a",
		Image:        "ubuntu",
		Command:      []string{},
		Args:         []string{},
		Capabilities: []string{},
		Privileged:   false,
		PrivEsc:      false,
		HostPID:      false,
		HostIPC:      false,
		HostNetwork:  false,
		RunAsUser:    0,
		Ports:        []string{},
		Pod:          "sharedps-pod2",
		// Node:         "",
		Compromised: 0,
	},
	"sharedps-pod-b": {
		StoreID:      "",
		Name:         "sharedps-pod-b",
		Image:        "ubuntu",
		Command:      []string{},
		Args:         []string{},
		Capabilities: []string{},
		Privileged:   false,
		PrivEsc:      false,
		HostPID:      false,
		HostIPC:      false,
		HostNetwork:  false,
		RunAsUser:    0,
		Ports:        []string{},
		Pod:          "sharedps-pod2",
		// Node:         "",
		Compromised: 0,
	},
	"sharedps-pod-c": {
		StoreID:      "",
		Name:         "sharedps-pod-c",
		Image:        "ubuntu",
		Command:      []string{},
		Args:         []string{},
		Capabilities: []string{},
		Privileged:   false,
		PrivEsc:      false,
		HostPID:      false,
		HostIPC:      false,
		HostNetwork:  false,
		RunAsUser:    0,
		Ports:        []string{},
		Pod:          "sharedps-pod1",
		// Node:         "",
		Compromised: 0,
	},
	"sys-ptrace-pod": {
		StoreID:      "",
		Name:         "sys-ptrace-pod",
		Image:        "ubuntu",
		Command:      []string{},
		Args:         []string{},
		Capabilities: []string{},
		Privileged:   false,
		PrivEsc:      false,
		HostPID:      false,
		HostIPC:      false,
		HostNetwork:  false,
		RunAsUser:    0,
		Ports:        []string{},
		Pod:          "sys-ptrace-pod",
		// Node:         "",
		Compromised: 0,
	},
	"tokenget-pod": {
		StoreID:      "",
		Name:         "tokenget-pod",
		Image:        "ubuntu",
		Command:      []string{},
		Args:         []string{},
		Capabilities: []string{},
		Privileged:   false,
		PrivEsc:      false,
		HostPID:      false,
		HostIPC:      false,
		HostNetwork:  false,
		RunAsUser:    0,
		Ports:        []string{},
		Pod:          "tokenget-pod",
		// Node:         "",
		Compromised: 0,
	},
	"tokenlist-pod": {
		StoreID:      "",
		Name:         "tokenlist-pod",
		Image:        "ubuntu",
		Command:      []string{},
		Args:         []string{},
		Capabilities: []string{},
		Privileged:   false,
		PrivEsc:      false,
		HostPID:      false,
		HostIPC:      false,
		HostNetwork:  false,
		RunAsUser:    0,
		Ports:        []string{},
		Pod:          "tokenlist-pod",
		// Node:         "",
		Compromised: 0,
	},
	"umh-core-pod": {
		StoreID:      "",
		Name:         "umh-core-pod",
		Image:        "ubuntu",
		Command:      []string{},
		Args:         []string{},
		Capabilities: []string{},
		Privileged:   false,
		PrivEsc:      false,
		HostPID:      false,
		HostIPC:      false,
		HostNetwork:  false,
		RunAsUser:    0,
		Ports:        []string{},
		Pod:          "umh-core-pod",
		// Node:         "",
		Compromised: 0,
	},
	"varlog-pod": {
		StoreID:      "",
		Name:         "varlog-pod",
		Image:        "ubuntu",
		Command:      []string{},
		Args:         []string{},
		Capabilities: []string{},
		Privileged:   false,
		PrivEsc:      false,
		HostPID:      false,
		HostIPC:      false,
		HostNetwork:  false,
		RunAsUser:    0,
		Ports:        []string{},
		Pod:          "varlog-pod",
		// Node:         "",
		Compromised: 0,
	},
}
